name: SkylyReport
version: '${project.version}'
main: fr.SkylyReport.SkylyReport

commands:
  customreport:
    description: Report a fdp !
    usage: /<command>
    permission: SkylyReport.customreport
  tempban:
    description: tempban a fdp !
    usage: /<command>
    permission: SkylyReport.tempban