# Created by Kisakay aka PeacefulTrees x Ezermoz

# CONFIG

# The webhook URL
webhook: "https://your-webhook-url.domain"

# The prefix of the server
globalprefix: "[SkyLy]"

# The date format on the webhook's embed
dateformat: "dd.MM.yyyy HH:mm"

# Choose the cooldown time in Sec
cooldowntime: "60"

# LANGUAGE

# %time% -> the cooldown time

# Quand la commande est executé par un Joueur
lang-console-cant-execute-command: "This command can only be executed by a player"

# Quand la commande est executé sans rentrer le joueur
lang-dont-type-player-command: "Entre le noms du joueur que tu veux signaler"

#Quand la commande est executé sans rentrer la raison
lang-dont-type-reason-command: "Entre la raison"

# Quand la commande est executé et que le joueur n'existe pas
lang-dont-found-player-command: "Le joueur est introuvable"

# Quand la commande est executé et que le temps n'est pas entrer
lang-dont-type-time-command: "Entre le temps s'il te plait"

# Quand la commande est exécuté avec succès !
lang-succes-work-command: "Tu viens de signaler le joueur."

# Quand la commande "/tempban" est executé avec succès !
lang-succes-work-2-command: "Tu viens de bannir le joueur."

# Quand le joueur tente de se signaler lui-même !
lang-player-self-command: "Tu ne peux pas t'auto report !"

# Quand le joueur executant la commande est en cooldown !
lang-player-cooldown-command: "Vous devez attendre %time% secondes avant de faire la commande !"

# /tempban
lang-dont-type-player-2-command: "Entre le noms du joueur que tu veux ban"
lang-dont-type-time-2-command: "Entre le temps s'il te plait"
lang-dont-type-reason-2-command: "Entre la raison du bannisement"
lang-dont-found-player-2-command: "Le joueur est introuvable"

# MESSAGE

# %player% -> the execute of the command
# %reason% -> the reason of the report
# %targetuser% -> the pottential cheater
# %date% -> the date formatted with "dateformat"
# 🛑 Use "\\n" not "\n" !

msg-content-webhook: ":mega: ||@here||"

msg-title-embed-webhook: "Report de %player%"

msg-description-embed-webhook: "Le report de **%player%** qui signale le joueur **%targetuser%** a `%date%`\\nPour la raison :\\n**%reason%**"

msg-logo-embed-webhook: "https://media.discordapp.net/attachments/1073309804493287585/1097644114943684728/Logo_S.png"

msg-logo-avatar-webhook: "https://media.discordapp.net/attachments/1073309804493287585/1097644114943684728/Logo_S.png"

msg-username-webhook: "SkyLy"

msg-footer-text-embed-webhook: "Latest skyly.fr report detected - The server is currently on"

msg-footer-icon-embed-webhook: "https://media.discordapp.net/attachments/1073309804493287585/1097644114943684728/Logo_S.png"

msg-thumbnail-player-head-api-webhook: "https://mc-heads.net/avatar/%player%"