name: SkylyReport
version: '1.0.1-SNAPSHOT'
main: fr.SkylyReport.SkylyReport

commands:
  customreport:
    description: Report a user !
    usage: /<command>
  tempban:
    description: tempban a user !
    usage: /<command>
    permission: SkylyReport.tempban