name: SkylyReport
version: '1.2-RELEASE'
main: fr.SkylyReport.SkylyReport

commands:
  creport:
    description: Report a user !
    usage: /<command>
  ctempban:
    description: tempban a user !
    usage: /<command>
    permission: SkylyReport.tempban